// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSecretPy() {
  return window['go']['main']['App']['LoadSecretPy']();
}

export function SaveSecretPy(arg1) {
  return window['go']['main']['App']['SaveSecretPy'](arg1);
}
