// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {config} from '../models';

export function ConnectOBS():Promise<types.StatusMessage>;

export function GetInfoWindowConfig():Promise<types.StatusMessage>;

export function GetSceneItems():Promise<types.StatusMessage>;

export function GetVideoOutputScreenshot(arg1:string):Promise<types.StatusMessage>;

export function GetVideoOutputSettings():Promise<config.GetVideoSettingsResponse>;

export function GetWindowConfig():Promise<types.StatusMessage>;

export function LoadSecretPy():Promise<types.SecretPy>;

export function SaveSecretPy(arg1:types.SecretPy):Promise<types.StatusMessage>;

export function WriteInfoWindowConfig(arg1:types.InfoWindowData):Promise<types.StatusMessage>;

export function WriteMovableWindowNames(arg1:Array<string>):Promise<types.StatusMessage>;

export function WriteWindowConfig(arg1:types.WindowConfig):Promise<types.StatusMessage>;
