// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectOBS() {
  return window['go']['main']['App']['ConnectOBS']();
}

export function GetInfoWindowConfig() {
  return window['go']['main']['App']['GetInfoWindowConfig']();
}

export function GetSceneItems() {
  return window['go']['main']['App']['GetSceneItems']();
}

export function GetVideoOutputScreenshot(arg1) {
  return window['go']['main']['App']['GetVideoOutputScreenshot'](arg1);
}

export function GetVideoOutputSettings() {
  return window['go']['main']['App']['GetVideoOutputSettings']();
}

export function GetWindowConfig() {
  return window['go']['main']['App']['GetWindowConfig']();
}

export function LoadSecretPy() {
  return window['go']['main']['App']['LoadSecretPy']();
}

export function SaveSecretPy(arg1) {
  return window['go']['main']['App']['SaveSecretPy'](arg1);
}

export function WriteInfoWindowConfig(arg1) {
  return window['go']['main']['App']['WriteInfoWindowConfig'](arg1);
}

export function WriteWindowConfig(arg1) {
  return window['go']['main']['App']['WriteWindowConfig'](arg1);
}
